const express = require("express");
const cors = require("cors");
const auth = require("./routes/auth");
const invoices = require("./routes/invoices");
const app = express();
app.use(cors());
app.use(express.json());
app.use("/auth", auth);
app.use("/invoices", invoices);
app.listen(5000, () => console.log("Backend running on 5000"));